name: robomimic_mixed_image
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    agentview_image:
      shape: [3, 84, 84]
      type: rgb
    # robot0_eye_in_hand_image:
    #   shape: [3, 84, 84]
    #   type: rgb
    robot0_eef_pos:
      shape: [3]
      # type default: low_dim
    robot0_eef_quat:
      shape: [4]
    robot0_gripper_qpos:
      shape: [2]
  action: 
    shape: [10]
obs_dim: 19
action_dim: 10
keypoint_dim: 3

obs_keys: &obs_keys ['robot0_gripper_qpos']
task_name: &task_name mixed
dataset_type: &dataset_type ph
# dataset_path: &dataset_path data/robomimic/datasets/${task.task_name}/${task.dataset_type}/low_dim_abs.hdf5
abs_action: &abs_action True

env_runner:
  _target_: diffusion_policy.env_runner.robomimic_image_runner_ae_mixed.RobomimicImageRunnerAEMixed
  n_train: &n_train 6
  n_test: &n_test 50
  n_train_vis: &n_train_vis 2
  n_test_vis: &n_test_vis 4
  test_start_seed: &test_start_seed 100000
  train_start_idx: &train_start_idx 0
  fps: &fps 10
  crf: &crf 22
  n_envs: &n_envs 28
  max_steps: &max_steps ${eval:'500 if "${task.dataset_type}" == "mh" else 400'}
  output_dir: &output_dir
  runners:
  - _target_: diffusion_policy.env_runner.robomimic_image_runner_ae.RobomimicImageRunnerAE
    dataset_path: data/robomimic/datasets/lift/${task.dataset_type}/image_abs.hdf5
    obs_keys: *obs_keys
    n_train: *n_train
    n_train_vis: *n_train_vis
    train_start_idx: *train_start_idx
    n_test: *n_test
    n_test_vis: *n_test_vis
    test_start_seed: *test_start_seed
    # use python's eval function as resolver, single-quoted string as argument
    max_steps: *max_steps
    n_obs_steps: ${n_obs_steps}
    n_action_steps: ${n_action_steps}
    n_latency_steps: ${n_latency_steps}
    render_hw: [128,128]
    fps: *fps
    crf: *crf
    past_action: ${past_action_visible}
    abs_action: *abs_action
    n_envs: *n_envs
    output_dir: *output_dir
  - _target_: diffusion_policy.env_runner.robomimic_image_runner_ae.RobomimicImageRunnerAE
    dataset_path: data/robomimic/datasets/can/${task.dataset_type}/image_abs.hdf5
    obs_keys: *obs_keys
    n_train: *n_train
    n_train_vis: *n_train_vis
    train_start_idx: *train_start_idx
    n_test: *n_test
    n_test_vis: *n_test_vis
    test_start_seed: *test_start_seed
    # use python's eval function as resolver, single-quoted string as argument
    max_steps: *max_steps
    n_obs_steps: ${n_obs_steps}
    n_action_steps: ${n_action_steps}
    n_latency_steps: ${n_latency_steps}
    render_hw: [128,128]
    fps: *fps
    crf: *crf
    past_action: ${past_action_visible}
    abs_action: *abs_action
    n_envs: *n_envs
    output_dir: *output_dir
  - _target_: diffusion_policy.env_runner.robomimic_image_runner_ae.RobomimicImageRunnerAE
    dataset_path: data/robomimic/datasets/square/${task.dataset_type}/image_abs.hdf5
    obs_keys: *obs_keys
    n_train: *n_train
    n_train_vis: *n_train_vis
    train_start_idx: *train_start_idx
    n_test: *n_test
    n_test_vis: *n_test_vis
    test_start_seed: *test_start_seed
    # use python's eval function as resolver, single-quoted string as argument
    max_steps: *max_steps
    n_obs_steps: ${n_obs_steps}
    n_action_steps: ${n_action_steps}
    n_latency_steps: ${n_latency_steps}
    render_hw: [128,128]
    fps: *fps
    crf: *crf
    past_action: ${past_action_visible}
    abs_action: *abs_action
    n_envs: *n_envs
    output_dir: *output_dir

dataset: 
  _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.MixedRobomimicReplayImageDataset
  datasets:
    - _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageLanguageDataset
      shape_meta: *shape_meta
      dataset_path: data/robomimic/datasets/lift/${task.dataset_type}/image_abs.hdf5
      horizon: ${horizon}
      pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
      pad_after: ${eval:'${n_action_steps}-1'}
      n_obs_steps: ${dataset_obs_steps}
      abs_action: *abs_action
      rotation_rep: rotation_6d
      use_legacy_normalizer: False
      use_cache: True
      seed: 42
      val_ratio: 0.02

    - _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageLanguageDataset
      shape_meta: *shape_meta
      dataset_path: data/robomimic/datasets/can/${task.dataset_type}/image_abs.hdf5
      horizon: ${horizon}
      pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
      pad_after: ${eval:'${n_action_steps}-1'}
      n_obs_steps: ${dataset_obs_steps}
      abs_action: *abs_action
      rotation_rep: rotation_6d
      use_legacy_normalizer: False
      use_cache: True
      seed: 42
      val_ratio: 0.02

    - _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageLanguageDataset
      shape_meta: *shape_meta
      dataset_path: data/robomimic/datasets/square/${task.dataset_type}/image_abs.hdf5
      horizon: ${horizon}
      pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
      pad_after: ${eval:'${n_action_steps}-1'}
      n_obs_steps: ${dataset_obs_steps}
      abs_action: *abs_action
      rotation_rep: rotation_6d
      use_legacy_normalizer: False
      use_cache: True
      seed: 42
      val_ratio: 0.02